name: Create GitHub Release

on:
    push:
        branches: ["master"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

permissions:
    contents: write
    id-token: write
    actions: read

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: v${{ github.run_number }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
